version: '2.1'

services:
  alpine:
    image: a4neg/docker-xrdp:alpine
    build:
      context: alpine/
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}
    pids_limit: 300
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true
    ports:
      - "2389:3389"


  alpine_tag:
    extends: alpine
    image: a4neg/docker-xrdp:${ALPINE_TAG}

  fedora:
    image: a4neg/docker-xrdp:fedora
    build:
      context: fedora/
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}
    pids_limit: 300
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true
    ports:
      - "3389:3389"

  fedora_tag:
    extends: fedora
    image: a4neg/docker-xrdp:${FEDORA_TAG}

  openscap:
    image: a4neg/docker-xrdp:openscap
    build:
      context: fedora/openscap/
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}
    pids_limit: 300
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true
    ports:
      - "4389:3389"

  openscap_tag:
    extends: openscap
    image: a4neg/docker-xrdp:${OPENSCAP_TAG}
